### ISSUE TITLE
[Bug]: Invalid Spec Attribute Propagation when defining a Pipeline spec via `original_yaml_string`

### ISSUE THREAD

**Issue by korenyoni** [codefresh-io/terraform-provider-codefresh#112]
### What happened?

When defining a Pipeline spec via `original_yaml_string`, it will fail to run:

```bash
Running Codefresh YAML validation                                                                                                                                
Yaml validation errors:                                                                                                                                          
                                                                                                                                                                 
 222  error     "true" is not allowed                                                                                                                            
 222  error     "true" is not allowed                                                                                                                            
 222  error     "steps" must be an array                                                                                                                         
                                                                                                                                                                 
✖ 3 problems (3 errors, 0 warnings)                                                                                                                              
Visit https://codefresh.io/docs/docs/codefresh-yaml/steps/approval/ for steps documentation 
```

Even though the validator passes:

```bash
$ codefresh validate codefresh.yml
Yaml is valid!
```

Seemingly this is because the [spec attribute propagation logic in the pipeline resource](https://github.com/codefresh-io/terraform-provider-codefresh/blob/93243ac1c895eec4e88b75d24f037e4950a050ce/codefresh/resource_pipeline.go#L879), which exists in order to preserve the map ordering of `steps`, `stages`, and `hooks`, has a bug.

```yaml
[
  {
    "metadata": {
      "name": "terrtest2/new-pipeline",
      "labels": {
        "tags": [
          "terraform-added"
        ]
      },
      "projectId": "64326387d0df5183bcd1fc24",
      "revision": 5,
      "originalYamlString": "version: \"1.0\"\nsteps:\n\n    test:\n      image: alpine\n      when:  \n        steps:\n          any:\n            - name: test1\n              on:\n                - failure\n            - name: test2\n              on:\n                - failure",
      "accountId": "631d9fb7ad511643e9a9d69d",
      "created_at": "2023-04-09T07:04:39.465Z",
      "updated_at": "2023-04-09T07:44:24.088Z",
      "project": "terrtest2",
      "shortName": "new-pipeline",
      "id": "64326387d0df519a1ad1fc25"
    },
    "spec": {
      "concurrency": 1,
      "stages": [],
      "runtimeEnvironment": {},
      "steps": {
        "test": {
          "image": "alpine",
          "when": {
            "steps": {
              "any": [
                {
                  "name": "test1",
                  "true": [
                    "failure"
                  ]
                },
                {
                  "name": "test2",
                  "true": [
                    "failure"
                  ]
                }
              ]
            }
          }
        }
      },
      "hooks": {},
      "triggers": [],
      "permitRestartFromFailedSteps": true
    },
    "version": "1.0",
    "kind": "pipeline"
  }
]
```

### Version

`0.3.1`

### Relevant Terraform Configuration

```yaml
version: "1.0"
steps:
    test:
      image: alpine
      when:  
        steps:
          any:
            - name: test1
              on:
                - failure
            - name: test2
              on:
                - failure
```


```hcl
resource "codefresh_project" "test" {
  name = "terrtest2"

  tags = [
    "terraform-changed",
  ]
}

resource "codefresh_pipeline" "test" {
  name    = "${codefresh_project.test.name}/new-pipeline"
 
  original_yaml_string = file("${path.module}/codefresh.yml")
  
  tags = [
    "terraform-added",
  ]

  spec {
    concurrency = 1
  }
}
```
